// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqpduzxikexqqniqhwrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxcGR1enhpa2V4cXFuaXFod3JiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1Njk2NTEsImV4cCI6MjA2MDE0NTY1MX0.Gt9R7gg_bZEYv8WcQ7lFNVktWYavk7bv0vZfuYesB-I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);