// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bcpwjwfubnpchoscvrum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjcHdqd2Z1Ym5wY2hvc2N2cnVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1ODgyMDEsImV4cCI6MjA3NTE2NDIwMX0.yTegOVlV_yy1rsVorfBLbURcxuUBApNrpFsi8-P5bJA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);